version: '3'

services:
  node: &app_base
    image: node:15.10.0-alpine3.10 # dockerhubにすでに上がっている
    tty: true
    working_dir: /var/www
    volumes:
      - ./src:/var/www # ./srcをコンテナ内の/var/wwwにマウントする
    environment:
      PORT: 3000
      HOST: 0.0.0.0
    restart: always # エラーなどでコンテナが落ちた際に自動で再起動してくれる

  workspace:
    <<: *app_base
    ports:
      - "3000:3000" # localhost:3000にポートをマッピングする
    command: yarn dev # upする際に実行されるコマンド